# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog redes neuronales
email: a215215573@alumnos.unison.mx
description: > # this means to ignore newlines until "baseurl:"
  Blog para hablar de mis experiencias haciendo redes neuronales.
baseurl: "" # the subpath of your site, e.g. /blog
url: "bitbucket.org/sanlf/blog" # the base hostname & protocol for your site
github_username:  sanlf
bitbucket_username: sanlf

# Build settings
markdown: kramdown

theme: jekyll-theme-tactile
